quiet: False
disable-version-string: True
with-expecter: True
filename: "{{.InterfaceName}}_mock.go"
mockname: "Mock{{.InterfaceName}}"
outpkg: mocks
packages:
  github.com/jdiuwe/api-server-demo/store:
    interfaces:
      Store:
  github.com/jdiuwe/api-server-demo/cache:
    interfaces:
      Cache:
