services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - API_PORT=8080
      - CACHE_TTL=30m
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - backend
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
    hostname: postgres
    image: "postgres"
    container_name: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - backend
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - backend
volumes:
  db:
    driver: local
networks:
  backend:
    driver: bridge
